controllers:
    resource: ../src/Controller/
    type: attribute

tasks:
    path: /tasks
    controller: App\Controller\TaskController::index

register:
    path: /register
    controller: App\Controller\UserController::register

login:
    path: /login
    controller: App\Controller\LoginController::index

logout:
    path: /logout
    controller: App\Controller\LoginController::logout

